
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es1-depl
  labels:
    component: elasticsearch
    cluster: smonnet1
    instance: es1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        cluster: smonnet1
        instance: es1
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      - name: contenedor-smonnet1-es1
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: jaysot/elasticsearch:5.3.1
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        
        - name: CLUSTER_NAME
          value: "smonnet1"
        
        - name: DISCOVERY_SERVICE
          value: smonnet1-discovery
        ports:
        
        - containerPort: 9200
          name: port-9200
          protocol: TCP
        
        - containerPort: 9300
          name: port-9300
          protocol: TCP
        
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: logs
          mountPath: /usr/share/elasticsearch/logs
      volumes:
        - emptyDir: {}
          name: data
        - emptyDir: {}
          name: logs